micronaut:
  application:
    name: helloWorld

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    status:
      http-mapping:
        DOWN: 503
    disk-space:
      enabled: true
      threshold: 9000000MB
